name: CI

on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: login
        run: |
          docker login docker.pkg.github.com -u daler -p ${{ secrets.GITHUB_TOKEN }}
          docker build -t docker.pkg.github.com/lcdb/lcdb-wf/main:0.1 .
          docker push docker.pkg.github.com/lcdb/lcdb-wf/main:0.1

