name: CI

on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: conda install --file requirements.txt

