name: CI

on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: |
          conda config --add channels defaults
          conda config --add channels bioconda
          conda config --add channels conda-forge
          conda install python star

      - name: Cache conda env
        id: cache-conda
        uses: actions/cache@v1
        with:
          path: /opt/conda/env
          key: v1
